// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://baiywkdtlozrysbmngdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhaXl3a2R0bG96cnlzYm1uZ2R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MjM1ODUsImV4cCI6MjA1Nzk5OTU4NX0.rS61Dr6JzB5jvXqyKOfxA-gSCOSS3YFpFeNThk2gdtQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);